#!/usr/bin/env python3
"""Generate the track line as GEOMETRY: models/track_line/model.sdf gets one
short black box segment per centerline sample, laid flat on the floor.

Why geometry and not a floor texture: under this laptop's mandatory software
rendering (LIBGL_ALWAYS_SOFTWARE=1), ogre2 blurs floor textures viewed at the
camera's shallow angle so hard that a 5 cm line vanishes entirely (tested
2026-07-12 at 1024px and 256px; albedo_map also only loads from absolute
paths). Plain colored geometry — like the old empty_test strip — renders
crisply, so the line is boxes.

The centerline is a list of (x, y) points in meters. The random track
generator (step 4) only needs to replace centerline_points(); everything
else stays.

Usage: python3 generate_track.py
"""
import math
from pathlib import Path

LINE_WIDTH_M = 0.05   # same width as the empty_test strip was
LINE_THICK_M = 0.002
SEGMENT_Z = 0.003     # floor panel top is at 0.002; sit 1 mm above it
N_POINTS = 128


def centerline_points():
    """Fixed oval, radii 1.2 x 0.8 m, centered on the plane."""
    return [
        (1.2 * math.cos(2 * math.pi * i / N_POINTS),
         0.8 * math.sin(2 * math.pi * i / N_POINTS))
        for i in range(N_POINTS)
    ]


def segments(points):
    """One box per consecutive point pair, 30% overlap to hide seams."""
    for i, (x0, y0) in enumerate(points):
        x1, y1 = points[(i + 1) % len(points)]
        length = math.hypot(x1 - x0, y1 - y0) * 1.3
        yaw = math.atan2(y1 - y0, x1 - x0)
        yield (x0 + x1) / 2, (y0 + y1) / 2, length, yaw


def main():
    visuals = []
    for i, (cx, cy, length, yaw) in enumerate(segments(centerline_points())):
        visuals.append(f'''      <visual name="seg_{i}">
        <pose>{cx:.4f} {cy:.4f} {SEGMENT_Z} 0 0 {yaw:.4f}</pose>
        <geometry>
          <box><size>{length:.4f} {LINE_WIDTH_M} {LINE_THICK_M}</size></box>
        </geometry>
        <material>
          <ambient>0 0 0 1</ambient>
          <diffuse>0 0 0 1</diffuse>
        </material>
      </visual>''')

    sdf = '''<?xml version="1.0"?>
<!-- GENERATED by scripts/generate_track.py — edit that script, not this file. -->
<sdf version="1.8">
  <model name="track_line">
    <static>true</static>
    <link name="link">
{visuals}
    </link>
  </model>
</sdf>
'''.format(visuals='\n'.join(visuals))

    out = Path(__file__).resolve().parent.parent / \
        'models' / 'track_line' / 'model.sdf'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sdf)
    print(f'wrote {out}: {len(visuals)} segments, '
          f'line {LINE_WIDTH_M} m wide')


if __name__ == '__main__':
    main()
